-- ------------------------------------------------------------------------
-- STEP 1: Database Setup & Table Creation
-- OBJECTIVE: To create the schema (table structure) that exactly matches the 
--            'Amazon Sale Report.csv' file. This prepares the PostgreSQL 
--            database to securely import and store the raw sales data.
-- ------------------------------------------------------------------------
CREATE TABLE amazon_sales (
    "index" INT,
    "Order ID" TEXT,
    "Date" TEXT,
    "Status" TEXT,
    "Fulfilment" TEXT,
    "Sales Channel " TEXT,
    "ship-service-level" TEXT,
    "Style" TEXT,
    "SKU" TEXT,
    "Category" TEXT,
    "Size" TEXT,
    "ASIN" TEXT,
    "Courier Status" TEXT,
    "Qty" INT,
    "currency" TEXT,
    "Amount" NUMERIC,
    "ship-city" TEXT,
    "ship-state" TEXT,
    "ship-postal-code" TEXT,
    "ship-country" TEXT,
    "promotion-ids" TEXT,
    "B2B" BOOLEAN,
    "fulfilled-by" TEXT,
    "Unnamed: 22" TEXT
);



/* ========================================================================
   PROJECT: E-Commerce Sales Performance Analysis
   DATASET: Amazon Sale Report
   TOOL USED: PostgreSQL
   DESCRIPTION: This script analyzes raw e-commerce data to find total revenue, 
                top-selling categories, regional demand, and operational efficiency.
   ======================================================================== */


-- ------------------------------------------------------------------------
-- QUERY 1: Total Orders and Total Revenue
-- OBJECTIVE: To find out the total number of orders processed and the 
--            total revenue (sales) generated by the company.
-- ------------------------------------------------------------------------
SELECT 
    COUNT("Order ID") AS Total_Orders,
    SUM("Amount") AS Total_Revenue
FROM amazon_sales
WHERE "Amount" IS NOT NULL;


-- ------------------------------------------------------------------------
-- QUERY 2: Top 5 Best-Selling Product Categories
-- OBJECTIVE: To identify which clothing categories (e.g., T-shirts, Shirts)
--            bring in the highest sales revenue for inventory planning.
-- ------------------------------------------------------------------------
SELECT 
    "Category", 
    SUM("Amount") AS Total_Sales
FROM amazon_sales
WHERE "Amount" IS NOT NULL
GROUP BY "Category"
ORDER BY Total_Sales DESC
LIMIT 5;


-- ------------------------------------------------------------------------
-- QUERY 3: Top 5 States with the Highest Sales Demand
-- OBJECTIVE: To find out which geographic locations generate the most 
--            revenue, helping the business in targeted marketing.
-- ------------------------------------------------------------------------
SELECT 
    "ship-state" AS State, 
    COUNT("Order ID") AS Total_Orders,
    SUM("Amount") AS Total_Sales
FROM amazon_sales
WHERE "Amount" IS NOT NULL
GROUP BY "ship-state"
ORDER BY Total_Sales DESC
LIMIT 5;


-- ------------------------------------------------------------------------
-- QUERY 4: Order Status Distribution (Checking Cancellation/Return Rate)
-- OBJECTIVE: To analyze the status of all orders (Shipped, Cancelled, Returned)
--            to assess the operational efficiency and potential losses.
-- ------------------------------------------------------------------------
SELECT 
    "Status", 
    COUNT("Order ID") AS Order_Count
FROM amazon_sales
GROUP BY "Status"
ORDER BY Order_Count DESC;